# Generated by Django 3.0.3 on 2020-07-04 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='svmp_d',
            old_name='nbPD_date',
            new_name='svmPD_date',
        ),
    ]
