# Generated by Django 3.0.3 on 2020-07-04 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_app', '0002_auto_20200704_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='svmb_d',
            old_name='nbBD_date',
            new_name='svmBD_date',
        ),
    ]
